// vue/src/components/defaults/stars/Three.vue
<template>
    <div class="flex items-center space-x-2">
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <EmptyStar />
      <EmptyStar />
    </div>
  </template>
  
  <script setup>
  import FilledStar from "../../icons/stars/FilledStar.vue";
  import EmptyStar from "../../icons/stars/EmptyStar.vue";
  </script>
  
  <style scoped>
  /* Add any scoped styles here if needed */
  </style>

// react/src/components/stars/Three.tsx
import React from "react";
import { EmptyStar, FilledStar } from "../svgs/starIcons";

const Three = () => {
  return (
    <div className="flex items-center space-x-2">
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <EmptyStar />
      <EmptyStar />
    </div>
  );
};

export default Three;
