// src/components/defaults/Drawer.tsx
import { motion } from "framer-motion";
import React, { FC, SetStateAction, useState } from "react";
import { NavLink } from "react-router-dom";
import HomeDropdown from "../dropdowns/HomeDropdown";
import { ArrowDown } from "../svgs/extras";

interface DrawerProps {
  setOpenDrawer: React.Dispatch<SetStateAction<boolean>>;
}

const Drawer: FC<DrawerProps> = ({ setOpenDrawer }) => {
  //   const [revealCategoryDropdown, setRevealCategoryDropdown] =
  //     useState<boolean>(false);
  //   const [revealBrandDropdown, setRevealBrandDropdown] =
  //     useState<boolean>(false);
  const [revealHomeDropdown, setRevealHomeDropdown] = useState<boolean>(false);
  const [isRotated, setIsRotated] = useState(false);

  const handleClick = () => {
    setRevealHomeDropdown(!revealHomeDropdown);
    setIsRotated(!isRotated);
  };

  return (
    <>
      <div className="fixed top-0 h-screen font-serif z-50 w-screen">
        <div className="">
          <motion.div
            className="flex flex-col space-y-[30px] bg-[#fff] h-screen w-[100%] pt-6 px-6 text-[18px] text-[#000]"
            initial={{ x: "100vw" }}
            animate={{ x: 0 }}
            transition={{ type: "ease", stiffness: 60 }}
          >
            <div className="flex justify-end text-[14px]">
              <p
                onClick={() => setOpenDrawer(false)}
                className="border border-[#808080] flex items-center justify-center h-8 w-8 rounded-full"
              >
                X
              </p>
            </div>
            <div className="space-y-4">
              <div
                onClick={handleClick}
                className="flex justify-between items-center"
              >
                <p>Home</p>
                <div
                  className={`transition-transform duration-300 ${
                    isRotated ? "rotate-0" : "-rotate-90"
                  }`}
                >
                  <ArrowDown />
                </div>
              </div>
              {revealHomeDropdown && <HomeDropdown />}
            </div>
            <div className="flex justify-between items-center">
              <p>Categories</p>
              <div className="-rotate-90">
                <ArrowDown />
              </div>
            </div>
            <div className="flex justify-between items-center">
              <p>Brands</p>
              <div className="-rotate-90">
                <ArrowDown />
              </div>
            </div>
            <NavLink to="/contact">Contact Us</NavLink>
            <p>Track Delivery</p>
            <NavLink to="/cart">Cart</NavLink>
            <NavLink to="/profile">Profile</NavLink>
          </motion.div>
        </div>
      </div>
    </>
  );
};

export default Drawer;

// vue/src/components/defaults/Drawer.vue
<template>
    <div class="fixed top-0 h-screen font-serif z-50 w-screen">
        <div>
            <transition name="slide">
                <div v-if="isDrawerOpen"
                    class="flex flex-col space-y-[30px] bg-[#fff] h-screen w-[100%] pt-6 px-6 text-[18px] text-[#000]">
                    <div class="flex justify-end text-[14px]">
                        <p @click="handleClose"
                            class="border border-[#808080] flex items-center justify-center h-6 w-6 rounded-full">
                            x
                        </p>
                    </div>
                    <div class="space-y-4">
                        <div @click="handleClick" class="flex justify-between items-center">
                            <p>Home</p>
                            <div :class="['transition-transform duration-300', isRotated ? 'rotate-0' : '-rotate-90']">
                                <ArrowDown />
                            </div>
                        </div>
                        <transition name="fade">
                            <HomeDropdown v-if="revealHomeDropdown" />
                        </transition>
                    </div>
                    <div class="flex justify-between items-center">
                        <p>Categories</p>
                        <div class="-rotate-90">
                            <ArrowDown />
                        </div>
                    </div>
                    <div class="flex justify-between items-center">
                        <p>Brands</p>
                        <div class="-rotate-90">
                            <ArrowDown />
                        </div>
                    </div>
                    <router-link v-if="props.active === 'footwear'" to="/shop">
                        Shop
                    </router-link>
                    <router-link v-if="props.active === 'wristwatch'" to="/tmp-2/shop">
                        Shop
                    </router-link>
                    <router-link v-if="props.active === 'furniture'" to="/tmp-3/shop">
                        Shop
                    </router-link>
                    <router-link v-if="props.active === 'clothes'" to="/tmp-4/shop">
                        Shop
                    </router-link>
                    <router-link v-if="props.active === 'tech'" to="/tmp-5/shop">
                        Shop
                    </router-link>
                    <router-link v-if="props.active === 'sports'" to="/tmp-6/shop">
                        Shop
                    </router-link>

                    <router-link v-if="props.active === 'footwear'" to="/cart">
                        Cart
                    </router-link>
                    <router-link v-if="props.active === 'wristwatch'" to="/tmp-2/cart">
                        Cart
                    </router-link>
                    <router-link v-if="props.active === 'furniture'" to="/tmp-3/cart">
                        Cart
                    </router-link>
                    <router-link v-if="props.active === 'clothes'" to="/tmp-4/cart">
                        Cart
                    </router-link>
                    <router-link v-if="props.active === 'tech'" to="/tmp-5/cart">
                        Cart
                    </router-link>
                    <router-link v-if="props.active === 'sports'" to="/tmp-6/cart">
                        Cart
                    </router-link>
                    <router-link v-if="props.active === 'footwear'" to="/footwear/contact"
                        class="hover:text-[#363f72] hover:font-semibold">
                        Contact Us
                    </router-link>
                    <router-link v-if="props.active === 'wristwatch'" to="/wristwatch/contact"
                        class="hover:text-[#363f72] hover:font-semibold">
                        Contact Us
                    </router-link>
                    <router-link v-if="props.active === 'furniture'" to="/furniture/contact"
                        class="hover:text-[#363f72] hover:font-semibold">
                        Contact Us
                    </router-link>
                    <router-link v-if="props.active === 'clothes'" to="/clothes/contact"
                        class="hover:text-[#363f72] hover:font-semibold">
                        Contact Us
                    </router-link>
                    <router-link v-if="props.active === 'tech'" to="/tech/contact"
                        class="hover:text-[#363f72] hover:font-semibold">
                        Contact Us
                    </router-link>
                    <router-link v-if="props.active === 'sports'" to="/sports/contact"
                        class="hover:text-[#363f72] hover:font-semibold">
                        Contact Us
                    </router-link>

                    <router-link v-if="props.active === 'footwear'" to="/footwear/track-order">
                        Track Delivery
                    </router-link>
                    <router-link v-if="props.active === 'wristwatch'" to="/wristwatch/track-order">
                        Track Delivery
                    </router-link>
                    <router-link v-if="props.active === 'furniture'" to="/furniture/track-order"> Track Delivery
                    </router-link>
                    <router-link v-if="props.active === 'clothes'" to="/clothes/track-order">
                        Track Delivery
                    </router-link>
                    <router-link v-if="props.active === 'tech'" to="/tech/track-order">
                        Track Delivery
                    </router-link>
                    <router-link v-if="props.active === 'sports'" to="/sports/track-order">
                        Track Delivery
                    </router-link>
                    <router-link to="/profile">Profile</router-link>
                </div>
            </transition>
        </div>
    </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import HomeDropdown from '../dropdowns/HomeDropdown.vue';
import ArrowDown from "../icons/extras/ArrowDown.vue";

import { defineEmits } from 'vue';

// Define the emits for your component
const emit = defineEmits(['close']);

// Method to handle close action
const handleClose = () => {
    emit('close'); // Emit the close event
};

// Props from parent component
const props = defineProps({
    setOpenDrawer: Function,
    active: String,
    isDrawerOpen: Boolean,
});

// Reactive state variables
const revealHomeDropdown = ref(false);
const isRotated = ref(false);

// Categories
const categories = ['footwear', 'wristwatch', 'furniture', 'clothes', 'tech', 'sports'];

// Get the correct path
const getPath = (base, activeCategory) => {
    return `/${activeCategory}/${base}`;
};

// Click handler for Home dropdown
const handleClick = () => {
    revealHomeDropdown.value = !revealHomeDropdown.value;
    isRotated.value = !isRotated.value;
};

// Watch the drawer open state
watch(() => props.isDrawerOpen, (newValue) => {
    isDrawerOpen.value = newValue;
});
</script>

<style scoped>
.slide-enter-active,
.slide-leave-active {
    transition: transform 0.3s ease;
}

.slide-enter,
.slide-leave-to {
    transform: translateX(100%);
}

.fade-enter-active,
.fade-leave-active {
    transition: opacity 0.3s ease;
}

.fade-enter,
.fade-leave-to {
    opacity: 0;
}
</style>
