// vue/src/views/footwear/Contact.vue
<template>
    <Header active="footwear" />
    <ContactTemplate themeColor="#000" />
    <Footer active="footwear" />
</template>

<script setup>
import ContactTemplate from "../../components/templates/ContactTemplate.vue";
import Header from "../../components/defaults/Header.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>

// react/src/pages/footwear/contact/index.tsx
import React from "react";
import Container from "../../../components/defaults/Container";
import ContactTemplate from "../../../components/templates/ContactTemplate";

const Contact = () => {
  return (
    <Container active="footwear">
      <ContactTemplate themeColor="#000" />
    </Container>
  );
};

export default Contact;
