// vue/src/components/defaults/stars/ThreeandHalf.vue
<template>
    <div class="flex items-center space-x-2">
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <HalfStar />
      <EmptyStar />
    </div>
  </template>
  
  <script setup>
  import FilledStar from "../../icons/stars/FilledStar.vue";
  import HalfStar from "../../icons/stars/HalfStar.vue"
  import EmptyStar from "../../icons/stars/EmptyStar.vue";
  </script>
  
  <style scoped>
  /* Add any scoped styles here if needed */
  </style>

// src/components/stars/ThreeandHalf.tsx
import { EmptyStar, FilledStar, HalfStar } from '../svgs/starIcons'

const ThreeandHalf = () => {
  return (
    <div className='flex items-center space-x-2'>
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <HalfStar />
      <EmptyStar />
    </div>
  )
}

export default ThreeandHalf
