// vue/src/views/wristwatch/Contact.vue
<template>
    <Header active="wristwatch" />
    <ContactTemplate themeColor="#ff4405" />
    <Footer active="wristwatch" />
</template>

<script setup>
import ContactTemplate from "../../components/templates/ContactTemplate.vue";
import Header from "../../components/defaults/Header.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>

// react/src/pages/wristwatch/contact/index.tsx
import React from 'react'
import Container from '../../../components/defaults/Container'
import ContactTemplate from '../../../components/templates/ContactTemplate'

const WristwatchContact = () => {
  return (
    <Container active="wristwatch">
      <ContactTemplate themeColor="#ff4405" />
    </Container>
  )
}

export default WristwatchContact
