// react/src/pages/clothes/cart/index.tsx

import Container from "../../../components/defaults/Container";
import CartTemplate from "../../../components/templates/CartTemplate";

const ClothesCart = () => {

  return (
    <Container active="clothes">
      <CartTemplate themeColor="#553a32" active="clothes" />
    </Container>
  );
};

export default ClothesCart;

// vue/src/views/clothes/Cart.vue
<script setup>
import Header from "../../components/defaults/Header.vue"
import CartTemplate from "../../components/templates/CartTemplate.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<template>
    <Header active="clothes" />
    <CartTemplate active="clothes" themeColor="#553a32" />
    <Footer active="clothes" />
</template>
