// react/src/pages/clothes/contact/index.tsx
import React from "react";
import Container from "../../../components/defaults/Container";
import ContactTemplate from "../../../components/templates/ContactTemplate";

const ClothesContact = () => {
  return (
    <Container active="clothes">
      <ContactTemplate themeColor="#553a32" />
    </Container>
  );
};

export default ClothesContact;

// vue/src/views/clothes/Contact.vue
<template>
    <Header active="clothes" />
    <ContactTemplate themeColor="#553a32" />
    <Footer active="clothes" />
</template>

<script setup>
import ContactTemplate from "../../components/templates/ContactTemplate.vue";
import Header from "../../components/defaults/Header.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>
