// react/src/pages/tech/cart/index.tsx

import Container from "../../../components/defaults/Container";
import CartTemplate from "../../../components/templates/CartTemplate";

const TechCart = () => {

  return (
    <Container active="tech">
      <CartTemplate themeColor="#3e4784" active="tech" />
    </Container>
  );
};

export default TechCart;

// vue/src/views/tech/Cart.vue
<script setup>
import Header from "../../components/defaults/Header.vue"
import CartTemplate from "../../components/templates/CartTemplate.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<template>
    <Header active="tech" />
    <CartTemplate themeColor="#3e4784" active="tech" />
    <Footer active="tech" />
</template>
