// react/src/pages/tech/contact/index.tsx
import Container from "../../../components/defaults/Container"
import ContactTemplate from "../../../components/templates/ContactTemplate"

const TechContact = () => {
  return (
    <Container active="tech">
      <ContactTemplate themeColor="#3e4784" />
    </Container>
  )
}

export default TechContact

// vue/src/views/tech/Contact.vue
<template>
    <Header active="tech" />
    <ContactTemplate themeColor="#3e4784" />
    <Footer active="tech" />
</template>

<script setup>
import ContactTemplate from "../../components/templates/ContactTemplate.vue";
import Header from "../../components/defaults/Header.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>
