// react/src/pages/furniture/cart/index.tsx

import Container from "../../../components/defaults/Container";
import CartTemplate from "../../../components/templates/CartTemplate";

const FurnitureCart = () => {

  return (
    <Container active="furniture">
      <CartTemplate themeColor="#0e9384" active="furniture" />
    </Container>
  );
};

export default FurnitureCart;

// vue/src/views/furniture/Cart.vue
<script setup>
import Header from "../../components/defaults/Header.vue"
import CartTemplate from "../../components/templates/CartTemplate.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<template>
    <Header active="furniture" />
    <CartTemplate themeColor="#0e9384" active="furniture" />
    <Footer active="furniture" />
</template>
