// react/src/pages/furniture/home/index.tsx
import React from "react"
import Container from "../../../components/defaults/Container"
import Categories from "../../../components/furniture/Categories"
import Hero from "../../../components/furniture/Hero"
import NewArrivals from "../../../components/furniture/NewArrivals"
import Reviews from "../../../components/furniture/Reviews"
import TopSelling from "../../../components/furniture/TopSelling"

const FurnitureHome = () => {
  return (
    <Container active="furniture">
        <Hero />
        <Categories />
        <NewArrivals />
        <TopSelling />
        <Reviews />
    </Container>
  )
}

export default FurnitureHome

// vue/src/views/furniture/Home.vue
<script setup>
import Header from '../../components/defaults/Header.vue'
import Footer from '../../components/defaults/Footer.vue'
import Hero from "../../components/furniture/Hero.vue"
import NewArrivals from "../../components/furniture/NewArrivals.vue"
import TopSelling from "../../components/furniture/TopSelling.vue"
import Reviews from "../../components/furniture/Reviews.vue"
import Categories from "../../components/furniture/Categories.vue"

</script>

<template>
    <Header active="furniture" />
    <Hero />
    <Categories />
    <NewArrivals />
    <TopSelling />
    <Reviews />
    <Footer active="furniture" />
</template>
