// react/src/pages/sports/cart/index.tsx
import Container from "../../../components/defaults/Container";
import CartTemplate from "../../../components/templates/CartTemplate";

const SportsCart = () => {
  return (
    <Container active="sports">
      <CartTemplate themeColor="#039855" active="sports" />
    </Container>
  );
};

export default SportsCart;

// vue/src/views/sports/Cart.vue
<script setup>
import Header from "../../components/defaults/Header.vue"
import CartTemplate from "../../components/templates/CartTemplate.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<template>
    <Header active="sports" />
    <CartTemplate themeColor="#039855" active="sports" />
    <Footer active="sports" />
</template>
