// src/pages/sports/contact/index.tsx
import Container from "../../../components/defaults/Container"
import ContactTemplate from "../../../components/templates/ContactTemplate"

const SportsContact = () => {
  return (
    <Container active="sports">
      <ContactTemplate themeColor="#039855" />
    </Container>
  )
}

export default SportsContact

// vue/src/views/sports/Contact.vue
<template>
    <Header active="sports" />
    <ContactTemplate themeColor="#039855" />
    <Footer active="sports" />
</template>

<script setup>
import ContactTemplate from "../../components/templates/ContactTemplate.vue";
import Header from "../../components/defaults/Header.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>
