// vue/src/views/footwear/Home.vue
<script setup>
import Header from '../../components/defaults/Header.vue'
import Hero from "../../components/footwear/Hero.vue"
import MiniGallery from "../../components/footwear/MiniGallery.vue"
import Categories from "../../components/footwear/Categories.vue"
import BestSeller from "../../components/footwear/BestSeller.vue"
import Reviews from "../../components/footwear/Reviews.vue"
</script>

<template>
    <Header active="footwear" />
    <div>
        <Hero />
        <MiniGallery />
        <Categories />
        <BestSeller />
        <Reviews />
    </div>
</template>

// src/pages/footwear/home/index.tsx
import Container from "../../../components/defaults/Container";
import BestSellers from "../../../components/footwear/BestSellers";
import Categories from "../../../components/footwear/Categories";
import Hero from "../../../components/footwear/Hero";
import MiniGallery from "../../../components/footwear/MiniGallery";
import Reviews from "../../../components/footwear/Reviews";

const FootwearHome = () => {
  return (
    <Container active="footwear">
      <Hero />
      <MiniGallery />
      <Categories />
      <BestSellers />
      <Reviews />
    </Container>
  );
};

export default FootwearHome;
