// vue/src/views/furniture/Contact.vue
<template>
    <Header active="furniture" />
    <ContactTemplate themeColor="#0e9384" />
    <Footer active="furniture" />
</template>

<script setup>
import ContactTemplate from "../../components/templates/ContactTemplate.vue";
import Header from "../../components/defaults/Header.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>

// react/src/pages/furniture/contact/index.tsx

import Container from "../../../components/defaults/Container"
import ContactTemplate from "../../../components/templates/ContactTemplate"

const FurnitureContact = () => {
  return (
    <Container active="furniture">
      <ContactTemplate themeColor="#0e9384" />
    </Container>
  )
}

export default FurnitureContact
