// vue/src/views/wristwatch/Cart.vue
<script setup>
import Header from "../../components/defaults/Header.vue"
import CartTemplate from "../../components/templates/CartTemplate.vue"
import Footer from "../../components/defaults/Footer.vue"
</script>

<template>
    <Header active="wristwatch" />
    <CartTemplate themeColor="#ff4405" active="wristwatch" />
    <Footer active="wristwatch" />
</template>

// react/src/pages/wristwatch/cart/index.tsx
import Container from "../../../components/defaults/Container";
import CartTemplate from "../../../components/templates/CartTemplate";

const WristwatchCart = () => {

  return (
    <Container active="wristwatch">
      <CartTemplate
        themeColor="#ff4405"
        active="wristwatch"
      />
    </Container>
  );
};

export default WristwatchCart;
