// vue/src/components/defaults/Header.vue
<script setup>
import { ref, defineProps } from 'vue';
import { useRouter } from 'vue-router';

import AccountIcon from "../icons/AccountIcon.vue";
import CartIcon from "../icons/CartIcon.vue";
import CaretDown from "../icons/CaretDown.vue";
import SearchIcon from "../icons/SearchIcon.vue";
import ShopIcon from "../icons/ShopIcon.vue";
import MobileHamburger from "../icons/MobileHamburger.vue";

import CategoriesDropdown from '../dropdowns/CategoriesDropdown.vue';
import BrandDropdown from '../dropdowns/BrandDropdown.vue';
import HomeDropdown from '../dropdowns/HomeDropdown.vue';
import Drawer from './Drawer.vue';
import Ad from './Ad.vue';

const props = defineProps({
  active: {
    type: String,
    required: true
  }
});

const revealCategoryDropdown = ref(false);
const revealBrandDropdown = ref(false);
const revealHomeDropdown = ref(false);
const openDrawer = ref(false);
const closeAd = ref(false);

const router = useRouter();

function toggleDropdown(target) {
  revealHomeDropdown.value = target === 'home' ? !revealHomeDropdown.value : false;
  revealCategoryDropdown.value = target === 'category' ? !revealCategoryDropdown.value : false;
  revealBrandDropdown.value = target === 'brand' ? !revealBrandDropdown.value : false;
}

</script>

<template>
  <div class="border-b-2 border-[#ccc] shadow-md fixed w-full z-50 bg-white">
    <Ad v-if="!closeAd" @close="closeAd = true" />

    <div class="w-[90vw] mx-auto py-3 flex justify-between items-center">
      <div class="flex items-center space-x-10">
        <router-link to="/">
          <img src="/assets/logo.png" alt="logo" class="max-w-[48px] max-h-[48px]" />
        </router-link>

        <div class="lg:flex hidden space-x-8">
          <div @click="toggleDropdown('home')"
            class="flex items-center space-x-2 cursor-pointer hover:text-[#363f72] hover:font-semibold">
            <h2>Home</h2>
            <CaretDown />
          </div>

          <div @click="toggleDropdown('category')"
            class="flex items-center space-x-2 cursor-pointer hover:text-[#363f72] hover:font-semibold">
            <h2>Categories</h2>
            <CaretDown />
          </div>

          <div @click="toggleDropdown('brand')"
            class="flex items-center space-x-2 cursor-pointer hover:text-[#363f72] hover:font-semibold">
            <h2>Brands</h2>
            <CaretDown />
          </div>

          <router-link v-if="props.active === 'footwear'" to="/footwear/contact"
            class="hover:text-[#363f72] hover:font-semibold">
            Contact Us
          </router-link>
          <router-link v-if="props.active === 'wristwatch'" to="/wristwatch/contact"
            class="hover:text-[#363f72] hover:font-semibold">
            Contact Us
          </router-link>
          <router-link v-if="props.active === 'furniture'" to="/furniture/contact"
            class="hover:text-[#363f72] hover:font-semibold">
            Contact Us
          </router-link>
          <router-link v-if="props.active === 'clothes'" to="/clothes/contact"
            class="hover:text-[#363f72] hover:font-semibold">
            Contact Us
          </router-link>
          <router-link v-if="props.active === 'tech'" to="/tech/contact"
            class="hover:text-[#363f72] hover:font-semibold">
            Contact Us
          </router-link>
          <router-link v-if="props.active === 'sports'" to="/sports/contact"
            class="hover:text-[#363f72] hover:font-semibold">
            Contact Us
          </router-link>
        </div>
      </div>

      <div class="lg:hidden block" @click="openDrawer = true">
        <MobileHamburger />
      </div>

      <div class="lg:flex hidden items-center space-x-8">
        <div class="input border flex items-center rounded-full py-1.5 px-5 space-x-3">
          <SearchIcon />
          <input type="text" placeholder="Search" class="border-none outline-none placeholder:text-[#333] bg-inherit" />
        </div>

        <router-link v-if="props.active === 'footwear'" to="/shop">
          <ShopIcon />
        </router-link>
        <router-link v-if="props.active === 'wristwatch'" to="/tmp-2/shop">
          <ShopIcon />
        </router-link>
        <router-link v-if="props.active === 'furniture'" to="/tmp-3/shop">
          <ShopIcon />
        </router-link>
        <router-link v-if="props.active === 'clothes'" to="/tmp-4/shop">
          <ShopIcon />
        </router-link>
        <router-link v-if="props.active === 'tech'" to="/tmp-5/shop">
          <ShopIcon />
        </router-link>
        <router-link v-if="props.active === 'sports'" to="/tmp-6/shop">
          <ShopIcon />
        </router-link>

        <router-link v-if="props.active === 'footwear'" to="/cart">
          <CartIcon />
        </router-link>
        <router-link v-if="props.active === 'wristwatch'" to="/tmp-2/cart">
          <CartIcon />
        </router-link>
        <router-link v-if="props.active === 'furniture'" to="/tmp-3/cart">
          <CartIcon />
        </router-link>
        <router-link v-if="props.active === 'clothes'" to="/tmp-4/cart">
          <CartIcon />
        </router-link>
        <router-link v-if="props.active === 'tech'" to="/tmp-5/cart">
          <CartIcon />
        </router-link>
        <router-link v-if="props.active === 'sports'" to="/tmp-6/cart">
          <CartIcon />
        </router-link>

        <router-link to="/profile">
          <AccountIcon />
        </router-link>
      </div>
    </div>

    <transition name="fade" mode="out-in">
      <HomeDropdown v-if="revealHomeDropdown" />
    </transition>
    <transition name="fade" mode="out-in">
      <CategoriesDropdown v-if="revealCategoryDropdown" :active="props.active" />
    </transition>
    <transition name="fade" mode="out-in">
      <BrandDropdown v-if="revealBrandDropdown" :active="props.active" />
    </transition>

    <Drawer v-if="openDrawer" :active="props.active" @close="openDrawer = false" :isDrawerOpen="openDrawer" />
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.6s, transform 0.6s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>

// react/src/components/defaults/Header.tsx
import { FC, useState } from "react";
import {
  AccountIcon,
  CaretDown,
  CartIcon,
  MobileHamburger,
  SearchIcon,
  ShopIcon,
} from "../svgs/headerIcons";
import CategoriesDropdown from "../dropdowns/CategoriesDropdown";
import BrandDropdown from "../dropdowns/BrandDropdown";
import HomeDropdown from "../dropdowns/HomeDropdown";
import { NavLink } from "react-router-dom";
import Drawer from "./Drawer";
import { motion } from "framer-motion";
import Ad from "./Ad";


interface HeaderProps {
  active: string;
}

const dropdownVariants = {
  initial: { opacity: 0, y: -20 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -10, transition: { duration: 0.6 } },
};

const Header: FC<HeaderProps> = ({ active }) => {
  const [revealCategoryDropdown, setRevealCategoryDropdown] =
    useState<boolean>(false);
  const [revealBrandDropdown, setRevealBrandDropdown] =
    useState<boolean>(false);
  const [revealHomeDropdown, setRevealHomeDropdown] = useState<boolean>(false);
  const [openDrawer, setOpenDrawer] = useState<boolean>(false);
  const [closeAd, setCloseAd] = useState<boolean>(false)

  return (
    <div className="border-b-2 border-[#ccc] shadow-md fixed w-[100%] z-50 bg-[#fff]">
      {!closeAd && <Ad setCloseAd={setCloseAd} />}
      <div className="w-[90vw] mx-auto py-3 flex justify-between items-center">
        <div className="flex items-center space-x-10">
          <NavLink to="/">
            <img
              src="/assets/logo.png"
              alt="logo"
              className="max-w-[48px] max-h-[48px]"
            />
          </NavLink>
          <div className="lg:flex hidden space-x-8">
            <div
              onClick={() => {
                if (revealBrandDropdown || revealCategoryDropdown) {
                  setRevealBrandDropdown(false);
                  setRevealCategoryDropdown(false);
                  setRevealHomeDropdown(!revealHomeDropdown);
                } else {
                  setRevealHomeDropdown(!revealHomeDropdown);
                }
              }}
              className="flex items-center space-x-2 hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out cursor-pointer"
            >
              <h2>Home</h2>
              <CaretDown />
            </div>
            <div
              className="flex items-center space-x-2 cursor-pointer hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
              onClick={() => {
                if (revealBrandDropdown || revealHomeDropdown) {
                  setRevealBrandDropdown(false);
                  setRevealHomeDropdown(false);
                  setRevealCategoryDropdown(!revealCategoryDropdown);
                } else {
                  setRevealCategoryDropdown(!revealCategoryDropdown);
                }
              }}
            >
              <h2>Categories</h2>
              <CaretDown />
            </div>
            <div
              className="flex items-center space-x-2 cursor-pointer hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
              onClick={() => {
                if (revealCategoryDropdown || revealHomeDropdown) {
                  setRevealCategoryDropdown(false);
                  setRevealHomeDropdown(false);
                  setRevealBrandDropdown(!revealBrandDropdown);
                } else {
                  setRevealBrandDropdown(!revealBrandDropdown);
                }
              }}
            >
              <h2>Brands</h2>
              <CaretDown />
            </div>
            {active === "footwear" && (
              <NavLink
                className="hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
                to="/contact"
              >
                Contact us
              </NavLink>
            )}
            {active === "wristwatch" && (
              <NavLink
                className="hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
                to="/tmp-2/contact"
              >
                Contact us
              </NavLink>
            )}
            {active === "furniture" && (
              <NavLink
                className="hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
                to="/tmp-3/contact"
              >
                Contact us
              </NavLink>
            )}
            {active === "clothes" && (
              <NavLink
                className="hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
                to="/tmp-4/contact"
              >
                Contact us
              </NavLink>
            )}
            {active === "tech" && (
              <NavLink
                className="hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
                to="/tmp-5/contact"
              >
                Contact us
              </NavLink>
            )}
            {active === "sports" && (
              <NavLink
                className="hover:text-[#363f72] hover:font-semibold transition-all duration-300 ease-in-out"
                to="/tmp-6/contact"
              >
                Contact us
              </NavLink>
            )}
          </div>
        </div>
        <div className="lg:hidden block" onClick={() => setOpenDrawer(true)}>
          <MobileHamburger />
        </div>

        <div className="lg:flex hidden items-center space-x-8">
          <div className="input border border-[#ccc] flex items-center rounded-full py-1.5 px-5 space-x-3">
            <SearchIcon />
            <input
              type="text"
              placeholder="Search"
              className="border-none outline-none placeholder:text-[#333] bg-inherit"
            />
          </div>
          {active === "footwear" && (
            <NavLink to="/shop">
              <ShopIcon />
            </NavLink>
          )}
          {active === "wristwatch" && (
            <NavLink to="/tmp-2/shop">
              <ShopIcon />
            </NavLink>
          )}
          {active === "furniture" && (
            <NavLink to="/tmp-3/shop">
              <ShopIcon />
            </NavLink>
          )}
          {active === "clothes" && (
            <NavLink to="/tmp-4/shop">
              <ShopIcon />
            </NavLink>
          )}
          {active === "tech" && (
            <NavLink to="/tmp-5/shop">
              <ShopIcon />
            </NavLink>
          )}
          {active === "sports" && (
            <NavLink to="/tmp-6/shop">
              <ShopIcon />
            </NavLink>
          )}
          {active === "footwear" && (
            <NavLink to="/cart">
              <CartIcon />
            </NavLink>
          )}
          {active === "wristwatch" && (
            <NavLink to="/tmp-2/cart">
              <CartIcon />
            </NavLink>
          )}
          {active === "furniture" && (
            <NavLink to="/tmp-3/cart">
              <CartIcon />
            </NavLink>
          )}
          {active === "clothes" && (
            <NavLink to="/tmp-4/cart">
              <CartIcon />
            </NavLink>
          )}
          {active === "tech" && (
            <NavLink to="/tmp-5/cart">
              <CartIcon />
            </NavLink>
          )}
          {active === "sports" && (
            <NavLink to="/tmp-6/cart">
              <CartIcon />
            </NavLink>
          )}
          <NavLink to="/profile">
            <AccountIcon />
          </NavLink>
        </div>
      </div>
      {revealHomeDropdown && (
        <motion.div
          variants={dropdownVariants}
          initial="initial"
          animate="animate"
          exit="exit"
          className="absolute w-full"
        >
          <HomeDropdown />
        </motion.div>
      )}
      {revealCategoryDropdown && (
        <motion.div
          variants={dropdownVariants}
          initial="initial"
          animate="animate"
          exit="exit"
          className="absolute w-full"
        >
          <CategoriesDropdown active={active} />
        </motion.div>
      )}
      {revealBrandDropdown && (
        <motion.div
          variants={dropdownVariants}
          initial="initial"
          animate="animate"
          exit="exit"
          className="absolute w-full"
        >
          <BrandDropdown />
        </motion.div>
      )}
      {openDrawer && <Drawer setOpenDrawer={setOpenDrawer} />}
    </div>
  );
};

export default Header;
