// react/src/components/stars/Five.tsx
import React from "react";
import { FilledStar } from "../svgs/starIcons";

const Five = () => {
  return (
    <div className="flex items-center space-x-2">
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
    </div>
  );
};

export default Five;

// vue/src/components/defaults/stars/Five.vue
<template>
    <div class="flex items-center space-x-2">
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
    </div>
  </template>
  
  <script setup>
  import FilledStar from "../../icons/stars/FilledStar.vue";
  </script>
  
  <style scoped>
  /* Add any scoped styles here if needed */
  </style>
