// react/src/components/stars/FourandHalf.tsx
import React from 'react'
import { FilledStar, HalfStar } from '../svgs/starIcons'

const FourandHalf = () => {
  return (
    <div className='flex items-center space-x-2'>
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <HalfStar />
    </div>
  )
}

export default FourandHalf

// vue/src/components/defaults/stars/FourandHalf.vue
<template>
    <div class="flex items-center space-x-2">
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <FilledStar />
      <HalfStar />
    </div>
  </template>
  
  <script setup>
  import FilledStar from "../../icons/stars/FilledStar.vue";
  import HalfStar from "../../icons/stars/HalfStar.vue";
  </script>
  
  <style scoped>
  /* Add any scoped styles here if needed */
  </style>
